### ISSUE TITLE
Implement Tukui.org

### ISSUE THREAD

**Issue by minikN** [erikabp123/ClassicAddonManager#10]
**Is your feature request related to a problem? Please describe.**
No, just a handy addition.

**Describe the solution you'd like**
Make the app work with addons from www.tukui.org (TukUI, ElvUI and many more..)

**Describe alternatives you've considered**
Using their Client, but that one ONLY works with their addons.

**Additional**
Should be quite easy using [this](https://www.tukui.org/api.php)

**Comment by erikabp123** [comment]
Hi, it's already in the works for the next patch!

**Comment by minikN** [comment]
Fastest reply ever.
