### ISSUE TITLE
Downloading certain Github addons that use releases are giving me an error as well

### ISSUE THREAD

**Issue by alecjpav** [erikabp123/ClassicAddonManager#12]
Take for instance this addon:
https://github.com/RagedUnicorn/wow-classic-gearmenu

I can add it fine with the "Use Releases" box checked, but when checking for update it gives me this error:
![1](https://user-images.githubusercontent.com/28431403/65554403-4c8e2200-dede-11e9-922c-bb9303880153.jpg)

I've tested another Github addon that uses releases and I'm getting the same error as well. 

Thank you for your continued support of this wonderful addon!

**Comment by erikabp123** [comment]
Can you please send me the managed.json file?

**Comment by alecjpav** [comment]
[managed.zip](https://github.com/erikabp123/ClassicAddonManager/files/3649773/managed.zip)

**Comment by alecjpav** [comment]
It seems GearMenu updated the second time, however the release zip file just has the files zipped without a GearMenu folder that they should be inside. So I cannot use this addon with ClassicAddonManager as it will just put those files directly into my Addons folder. It will also get the program stuck on "Attempting to remove addon" if you press the Remove button as well.

ClassicLFG (the other addon I tested) on the other hand does have a ClassicLFG folder in the release zip file, but it gives me the same error as above and does not download properly on the second attempt.

**Comment by erikabp123** [comment]
I know what the issues are now, So ClassicLFG doesn't actually have any files uploaded to the release, instead the author just marks the source code as a release and allows you to download the source code as a zip. The manager looks for a unique zip folder upload. And the problem with GearMenu is that it doesn't have a folder inside the zip, so when CAM extracts it doesn't extract a folder, instead it just ends up extracting the files. I will add fixes for these two situations as todos!

**Comment by alecjpav** [comment]
Wonderful, thanks so much! Really appreciate your work on this program.
