### ISSUE TITLE
Tukui/Elvui

### ISSUE THREAD

**Issue by AndehX** [erikabp123/ClassicAddonManager#13]
How exactly do you add these?  I tried pasting links into the addon manager, but it just tells me that it's an invalid url

**Comment by erikabp123** [comment]
Can you show me which link you're using?

Here is an example of tukui:

https://www.tukui.org/classic-addons.php?id=1

**Comment by AndehX** [comment]
Ok I've sorted it.  I was trying links from their github page.  Didn't realise it was a simple as using the URL to the download page on the website.
