### ISSUE TITLE
Self updater doesn't relaunch if using jar version

### ISSUE THREAD

**Issue by Nedlinin** [erikabp123/ClassicAddonManager#17]
**Describe the bug**
If you are using just the jar install and a system installation of Java, the self updater works but does not relaunch the application after update has been downloaded.

**To Reproduce**
1. Use older version of the .jar release.
2. Run it, download the update
3. See error when it tries to restart.

**Expected behavior**
Restarts successfully.

**Additional context**
https://github.com/erikabp123/ClassicAddonManager/blob/df0cd4bef2e94d24086403c613907e01c200f3f4/src/main/java/com/CAM/Updating/SelfUpdater.java#L125

Hardcoded path to Java executable.  Mine is located at C:\Program Files\AdoptOpenJDK\jdk-14.0.1.7-hotspot\bin\java.exe due to the version installed on my machine

**Comment by erikabp123** [comment]
Hey, im aware of this problem and Will fix it as soon as possible!

**Comment by erikabp123** [comment]
Should be addressed in newest version. However, you must have version 1.8 or newer
