### ISSUE TITLE
Addons removed from Interface Directory after update

### ISSUE THREAD

**Issue by HiImRob** [erikabp123/ClassicAddonManager#18]
It happens to me more and more often that Addons managed by WoW Classic Addon Manager are removed from Interface Directory after I update them. 

Unfortunately, I cannot pin the issue on one specific Addon, it rather depends on which Addon has an update available and even then it seems random on when it would disappears from the Interface Folder afterwards or not.

Another push on the "Update Addons" Button will not reinstall the Addon since it is still in the Managed Addons List within the app with a recent download timestamp. The only thing that helps is to remove it from the list and add it again. After that the Addon will be downloaded and installed as usual.

I hope you can help me pin down the issue and let me know if you need more information.

Maybe are already a few helpful facts:

* My addons are completely managed by your app
* I use the bundled .exe version you provide on the page
* A debug log of one case where the addon disappeared after update:

```
update available for: Details! Damage Meter Classic WoW by Terciob!
Attempting to fetch update ...
Successfully fetched new update!
Attempting install of addon Details! Damage Meter Classic WoW ...
Attempting uninstall of Details! Damage Meter Classic WoW ...
Looking for addon installation log ...
Loading installation log ...
Directories: [Details_DataStorage, Details, Details_Streamer, Details_TinyThreat]
Successfully loaded managed.json!
G:\Games\World of Warcraft\_classic_\Interface\AddOns\Details_DataStorage is valid directory: true
G:\Games\World of Warcraft\_classic_\Interface\AddOns\Details is valid directory: true
G:\Games\World of Warcraft\_classic_\Interface\AddOns\Details_Streamer is valid directory: true
G:\Games\World of Warcraft\_classic_\Interface\AddOns\Details_TinyThreat is valid directory: true
data/managed/Details! Damage Meter Classic WoW.json is valid file: true
Finished uninstall!
Attempting to log installation ...
Successfully logged installation!
downloads/Details! Damage Meter Classic WoW_Terciob_(DetailsClassic.1.13.5.211.142.zip).zip is valid file: true
Looking for addon installation log ...
Loading installation log ...
Directories: []
Successfully loaded managed.json!
Attempting to log rename ...
Successfully logged rename!
Successfully installed addon!
Attempting to save to managed.json ...
Successfully saved to managed.json!
```

**Comment by erikabp123** [comment]
Thank you for reporting this issue! 
This sounds like it might be related to either permission, a failed download, or a failed extraction of a download. I won't be able to test this properly and try to fix it until I get back from holiday and have a proper PC available, however in the meantime maybe you can provide me with some additional information:

1.) How long have you had this problem? Has this only been a problem with the newest update or have you perhaps experienced it with an older update?

2.) Which specific operating system are you using and in which language?

3.) Where is your wow classic exe located? Specifically, the full path to the interface folder is what I'm looking for. I'm mostly interested to find out if you have any special characters, spaces, or similar included in your path.

4.) When does this behavior occur? Only when adding a new addon or is it randomly when updating?

5.) What does the managed.json look like for an addon when this problem occurs? Is it identical with other addons or can you notice if some information is missing. For this, if you have a copy of you managed.json for one such occasion it would be great if you could send it to me. Additionally there is a ADDON_NAME.json file, if you could send a copy of that when an install goes wrong and a copy right after when you have done a successfull reinstall so I could compare those that would also be ideal.

This should help me get started on troubleshooting the problem, any additional information that you might think of is welcome.

**Comment by HiImRob** [comment]
Thank you for the quick response! 

I was waiting for the issue to reappear and I thought for a few days that I found away around it by putting both WoW and your app on a SSD. However, the issue showed its face again so here we go with the requested answers:

1.) I started using your app with version v0.78. But it was only for a short period until the newer release v0.8 came. I also cannot recall having issues with the older version. Maybe I can try to use the old version again and see if I can reproduce this issue.

2.) It's Windows 7 with English localization

3.) ```G:\Games\World of Warcraft\_classic_\Interface\AddOns\```

4.) I rarely add new addons, the issue appears randomly (so to seem) when I update them with the provided button. I have the feeling that it happens more often when more than 3 addons need an update.

5.) The managed.json looks completely normal after the failed update. To give you more context here are two addon entries of my recent update: 
```
        {
            "name": "Deadly Boss Mods (DBM)",
            "author": "MysticalOS",
            "origin": "https://www.curseforge.com/wow/addons/deadly-boss-mods",
            "lastUpdated": "Jul 22, 2020, 4:00:55 PM",
            "lastFileName": "Deadly Boss Mods (DBM)_MysticalOS_(DBM-Core-1.13.53-48-gf3befa4-classic.zip).zip",
            "releases": false,
            "lastUpdateCheck": "Jul 22, 2020, 4:00:54 PM",
            "projectId": 3358
        },
        {
            "name": "NeatPlates",
            "author": "Luxie",
            "origin": "https://www.curseforge.com/wow/addons/neatplates",
            "lastUpdated": "Jul 22, 2020, 4:01:04 PM",
            "lastFileName": "NeatPlates_Luxie_(NeatPlates-1.13.5.4.zip).zip",
            "releases": false,
            "lastUpdateCheck": "Jul 22, 2020, 4:01:04 PM",
            "projectId": 299093
        },
```
However, DBM was correctly installed whereas NeatPlates was gone from my Interface folder afterwards.

This is what I found in the NeatPlates.json after the failed update: 
```
[]
```
When I reinstalled it again in order to fix this issue as described in my initial comment it was filled again:
``` 
[
    "NeatPlates_Slim_Horizontal",
    "NeatPlates_Graphite",
    "NeatPlatesHub",
    "NeatPlates_BlizzardPlates",
    "NeatPlatesWidgets",
    "NeatPlates",
    "NeatPlates_Grey",
    "NeatPlates_Alvara",
    "NeatPlates_Quatre",
    "NeatPlates_Roth",
    "NeatPlates_Neon",
    "NeatPlates_Renaitre",
    "NeatPlates_ClassicPlates",
    "NeatPlates_Simple",
    "NeatPlates_Slim_Vertical"
]
```

**Comment by rrrrrrrrrrrrrrrrrrrrrrrr** [comment]
I am having the same issue. However, the only addon that seems to be getting deleted upon update is Details! Damage Meter
