### ISSUE TITLE
Linux & Retail wow support

### ISSUE THREAD

**Issue by mspykerez** [erikabp123/ClassicAddonManager#19]
Hi
Is there any plans for Linux support and also RETAIL WoW support ?

**Comment by erikabp123** [comment]
Hi, retail should be easy enough to implement. Linux I'm not so sure, it suffers from the same problem as Mac in terms of changes I would need to make. I'd like to have support for both Mac and Linux in the future however. I will look into it!

**Comment by erikabp123** [comment]
Next release will feature support for retail and PTRs among other features
