### ISSUE TITLE
auto-add to addon managing list & select release type

### ISSUE THREAD

**Issue by mspykerez** [erikabp123/ClassicAddonManager#20]
Any chance to add a 'scan' feature to scan the current wow addon directory and add them automatically to the managing addon list ?

Also would be great if we could select/ignore the type of releases we want, like RELEASE, BETA, ALPHA as curseforge puts it.

**Comment by erikabp123** [comment]
Scan I have been considering for a while, but it's just about figuring out how to do it. There should be an option to set it to only use releases. By default it should just use whatever is newest. I. E. Alpha or beta or releases
