### ISSUE TITLE
Can't find exe file

### ISSUE THREAD

**Issue by xaldron** [erikabp123/ClassicAddonManager#21]
Not so much a bug as a unexpected problem. I can't seem to find any .exe files in the directory. Any pointers?

**Comment by erikabp123** [comment]
Are you just now downloading it and can't find the exe? Or have you been using it for sometime and the exe randomly disappeared?

In the case of the former, make sure you download the zip called ClassicWowAddonManager. This is the correct file. Inside should be the exe. In the case of the latter it might have been removed by another program then. In that case check your antivirusprogram and download the zip file again and just copy the exe from it.

**Comment by xaldron** [comment]
Resolved. 

My bad, I had downloaded the source code zip and not the zip under releases. Thanks for the quick response, and thank you for a great addon manager!
