### ISSUE TITLE
Support for Gitlab hosted addons

### ISSUE THREAD

**Issue by matt-hagan** [erikabp123/ClassicAddonManager#22]
As you have support for github hosted addons, was wondering if there is support for gitlab planned at this time.

As the main ELVUI and TUKUI are hosted on gitlab, being able to update elv/tuk ui in the addonmanager  would be a lovely feature.

**Comment by erikabp123** [comment]
I have talked to the tukui author and he is going to add tukui and Elvui for retail to their api. Currently they are available for classic, but not retail. What this means is you can install and update them through the manager for classic. However in the meantime you have to manually update them for retail. I can add support for gitlab if that is a feature that you feel would add a lot. However the next update will be a very large change to the ui, which I'm about 80-90% done with. As such it won't be out for at least one or two weeks  as I won't release gitlab support before the ui, however I can probably add it as a part of the update.
