### ISSUE TITLE
Doesn't work with addons that contains :*"<>| in the title

### ISSUE THREAD

**Issue by FlayaN** [erikabp123/ClassicAddonManager#3]
**Describe the bug**
It doesnt work with addons if the name of the addon contains character that will generate invalid filename.

https://github.com/erikabp123/ClassicAddonManager/blob/bdfbed5e34ac1c1cb241762a241cd512c2beefad/src/main/java/com/CAM/DataCollection/Scraper.java#L126

This array needs more illegal chars: `:*"<>|`

![image](https://user-images.githubusercontent.com/964655/63637307-7fdd5700-c67b-11e9-891b-fc0beacb5aea.png)

**Version**
0.47

**To Reproduce**
1. Add this addon: https://www.curseforge.com/wow/addons/guidelime_sage
2. The name of the addon is resolved from the title of curseforge page, but the title contains invalid characters (in this case `|`)
3. It doesn't create a json file under `ClassicWowAddonManager\data\managed`
4. Addons looks like it's installed but it's not added in the Addons folder!
5. If I manually edit the name of the addon in `ClassicWowAddonManager\data\managed.json` and strip of the `|` in this case it works as expected!

**Expected behavior**
I expect it to take out invalid characters out of the addon name that prevents the addon from being installed

**Comment by erikabp123** [comment]
Thanks for the report, should be fixed and will be present in next update. If issue persists, let me know
