### ISSUE TITLE
curseforge/overwolf support

### ISSUE THREAD

**Issue by torkus** [erikabp123/ClassicAddonManager#30]
Quick question for my [list of wow addon managers](https://ogri-la.github.io/wow-addon-managers/), does ClassicAddonManager still support Curseforge after the Overwolf [API deprecation](https://mailchi.mp/overwolf/whats-new-with-overwolf-curseforge-november3)?

**Comment by erikabp123** [comment]
Has it rolled out yet? If so, then it still works

**Comment by torkus** [comment]
That's good to hear. The deprecation period has been reached.
