### ISSUE TITLE
Scrape error

### ISSUE THREAD

**Issue by MarkusKluge** [erikabp123/ClassicAddonManager#4]
**Describe the bug**
Updater stops if the URL of the addon got an not found error (404) or some other http error while fetching. I just had the problem with the addon "neat-plates" which got renamed to "neatplates" in the curse URL which resulted to this scrape 404 error. It should display the error message that the url is invalid or the url changed and maybe continue with the next addon.

**To Reproduce**
1. Add https://www.curseforge.com/wow/addons/neat-plates
2. Addon creator creator/curse changed URL to https://www.curseforge.com/wow/addons/neatplates
3. Fetch update with this Manager
4. Scrape 404 error appears

**Expected behavior**
Info message or popup saying that you should check/rename the URL (which means you should display the urls and make them changable without removing/readding them.

**Comment by erikabp123** [comment]
Will add a pop-up informing the user to validate whether URL has changed

**Comment by erikabp123** [comment]
New release tonight should address this issue
