### ISSUE TITLE
UI informations

### ISSUE THREAD

**Issue by MarkusKluge** [erikabp123/ClassicAddonManager#5]
**Is your feature request related to a problem? Please describe.**
Making sure that the download/installation was successfully by showing the numbers and the version timestamp.

**Describe the solution you'd like**
Show current version number and date of the addons in columns for the addons.

**Describe alternatives you've considered**
Maybe a UI that contains this information/functions like the UI screenshot on wowmatrix.com (the searching for AddOns feature isnt needed yet I guess)

**Comment by erikabp123** [comment]
Will look into, thanks!

**Comment by erikabp123** [comment]
Something like this coming in the next update
