### ISSUE TITLE
Stuck on "Updating addons" and debug shows nothing

### ISSUE THREAD

**Issue by roberth1990** [erikabp123/ClassicAddonManager#6]
Don't know when it started but now when I just click on "update addons", this is all that just shows up:

```
Running self updater ...
Checking for new release ...
No new release available!
Self Updater finished without finding any new updates!
Set debug to true
Updating addons ...
```

**Comment by voxxtelum** [comment]
I had the same problem but it was caused by an addon that was removed from WoW Interface, in my case Atlas World Map Classic.

**Comment by roberth1990** [comment]
> 
> 
> I had the same problem but it was caused by an addon that was removed from WoW Interface, in my case Atlas World Map Classic.

Yeah that was exactly my issue too, this manager needs to be able to just skip those and show the result as an error in the output log.

**Comment by erikabp123** [comment]
I experienced the same issue, I am currently working on a new release where the UI should never hang like it does now. There should also be more informative feedback as it relates to errors. It should be ready within the next couple of days, maybe tonight even.
