### ISSUE TITLE
Windows defender trigger

### ISSUE THREAD

**Issue by dariumz** [erikabp123/ClassicAddonManager#7]
Upon extracting the zip, windows Defender triggers with a warning for tiggre:plock

Might wanna take a look at that.

**Comment by itsSynn** [comment]
Just wanted to chime in and confirm this started firing for me this morning, as well. No warnings up until today, though.

**Comment by erikabp123** [comment]
Yes, I am aware of this problem. I am working on a new .exe to replace the old one. The new one hopefully shouldn't get flagged. Thanks for reporting!
