### ISSUE TITLE
New update flagged by Windows Defender

### ISSUE THREAD

**Issue by jonatronnn** [erikabp123/ClassicAddonManager#8]
Just updated using the autoupdate feature and the program was instantly flagged and quarantined as the following:

Behavior:Win32/Generic.QS!ml

Are you able to shed any light on what might be causing this?

**Comment by mattb1942** [comment]
Webroot flags the main exe as Tiggre Trojan Malware

**Comment by erikabp123** [comment]
I am aware of this issue, the .exe is actually just a launcher for the main .jar file. I am working on a new .exe atm but it might take a little time til I have one ready. Until then you will have to manually flag the .exe as okay

**Comment by erikabp123** [comment]
As to your question of why it is happening, the answer is likely that the .exe is originally a batch script (very simple one to just launch the .jar file) that was converted into an .exe, windows defender among others are prone to marking .exe that contain batch scripts as trojans (see [here](https://stackoverflow.com/questions/32168332/after-converting-batch-file-to-exe-windows-defender-shows-the-file-as-trojan-why) )

**Comment by erikabp123** [comment]
Can you try this temporary .exe? Should not get flagged @jonatronnn @mattb1942 
[CAM_LAUNCHER.zip](https://github.com/erikabp123/ClassicAddonManager/files/3567157/CAM_LAUNCHER.zip)

**Comment by mattb1942** [comment]
I can report that this does not get flagged by webroot with latest deep
scan and launches fine.

Regards,
Matt

**Comment by erikabp123** [comment]
@mattb1942 @jonatronnn I have a new .exe that I just need to test and I will release it if it works fine... So far no problems BUT it is x64 only... I tried compiling one that supports x32/64 but it was getting false positive (only on one AV but still)
